export const levelOne = [
  "What was your first impression of me?",
  "What do you think is the hardest part of what I do for a living",
  "What reality show do you think I'm most likely to binge watch? explain.",
  "Do I seem like a cat or dog person?",
  "What do my shoes tell you about me?",
  "Do I seem like more of a creative or analytical type? explain.",
  "How many speeding tickets do you think I've gotten in my life?",
  "Do I seem like someone who would get a name tattooed on myself?",
  "What do you think I'm most likely to splurge on?",
  "Finish the sentence: just by looking at you I'd think ____.",
  "What character would I play in a movie?",
  "Do I remind you of anyone?",
  "Who do you think my celebrity crush is?",
  "Do you think I've ever checked an ex's phone for evidence?",
  "What's the first thing you noticed about me?",
  "Do I seem like a coffee or tea person? Sweetened or unsweetened?",
  "What do you think my go to karaoke song is?",
  "If you were to buy me a present, knowing nothing about me other than what I look like, what would it be?",
  "What does my phone wallpaper tell you about me?",
  "Do I look kind? explain.",
  "Do you think I fall in love easily? why or why not?",
  "As a child, what do you think I wanted to be?",
  "Do you think I'm usually early, on time, or late to events? explain.",
  "What subject do you think I thrived in at school? Did I fail any?",
  "What compliment do you think I hear the most?",
  "Do I seem like a morning person or a night owl? why?",
  "What fast food restaurant do you think I'm most likely to drive through? What's my order?",
  "What is my body language telling you right now?",
  "What does my instagram tell you about me?",
  "Do you think plants thrive or die in my care? explain.",
  "On a scale of 1-10, how messy do you think my car is? 1 being clean 10 complete disaster",
  "Do you think I was popular in school? explain.",
  "Do you think I've ever been fired from a job? If so, what for?",
  "Do you think I intimidate others? why or why not?",
  "How likely am I to go camping? how high maintenance is my set up?",
  "What about me is most strange or unfamiliar to you?",
  "If myspace were still a thing, what would my profile song be?",
  "What about me intrigues you?",
  "What does my style tell you about me?",
  "Do you think I've ever had my heart broken?",
  "Do you think I've been in love?",
  "What is the worst assumption someone has made about you?",
  "What is your defining characteristic?",
  "What's the most pain you've ever been in that wasn't physical?",
  "How are you, really?",
  "What is the last thing your mom has lied to you about?",
  "What's your father's name and one thing about him?",
  "What have I tolerated from people in the past that I no longer have space for?",
  "Something that brought a smile to my face this week was ___.",
  "What are you feeling a lot of lately?",
  "What do you need right now but aren't communicating?",
  "What are you currently working through that others don't see?",
  "What was the biggest turning point in your dating life?",
  "What is your heart telling you?",
  "What is your most toxic trait you can admit to?",
  "Who in your life deserves the biggest thank you? Let them know if you can.",
  "What are you overthinking right now?",
  "What did you last relationship teach you about yourself?",
  "What belief about yourself no longer serves you?",
  "What do you need to forgive yourself for?",
  "What's the hardest lesson you've learned in love?",
  "You hurt me, but thank you for ___.",
  "Who in your life can you be your most vulnerable with?",
  "Which one of your parent's personality traits do you want to keep/let go of?",
  "Dear younger self: ____.",
  "Think of someone you admire. Why did this person come to mind?",
  "Are you lying to yourself about anything?",
  "What's your favorite part of yourself that isn't physical?",
  "What's the hardest part about dating you?",
  "I feel loved when ___.",
  "What is something you've learned about yourself this week?",
  "Self love is ___.",
  "What was the lesson in your most recent painful experience?",
  "I know I'm in love when ___.",
  "What's your favorite song lyric you can think of off the top of your head?",
  "How did you get over your first love?",
  "What's the best lesson an ex has ever taught you?",
  "Is there anyone who's changed your life but doesn't know it?",
  "What do you need right now, more than anything?",
  "When was the last time you felt lucky to be you?",
  "What do you need to accept today?",
  "When was the last time you felt most yourself?",
  "What's your mother's name and the most valuable lesson she's taught you thus far?",
  "What are you most grateful for in this current moment?",
  "What are you still trying to prove to yourself?",
  "What have you been taking for granted lately?",
  "Is there a feeling you miss?",
  "What would your younger self not believe about your life today?",
  "If you could have it your way: Who would you be with? Where would you be? And what would you be doing?",
  "What do you need to hear right now?",
  "What title would you give this chapter in your life?",
  "What dating advice would you give your younger self?",
  "What lesson should you have learned by now?",
  "When was the last time you were able to use your pain to help someone else?",
  "What would you never want to change about yourself?",
  "What question did this year leave you with?",
  "What about yourself is hardest to admit?",
  "What question are you trying to answer most in your life right now?",
  "Finish the sentences: strangers would describe me as _____. Only I know that I am ______",
  "When you're asked how are you, how often do you answer truthfully?",
  "Has a stranger ever changed your life?",
  "What is the most unexplainable thing that's ever happened to you?",
  "Describe your perfect day!",
  "Have you changed your mind about anything recently?",
  "What's been the best compliment a stranger has ever given you?",
  "What is a compliment you wish you received more frequently?",
  "What do you crave more of?",
  "What has been your earliest recollection of happiness?",
  "What are you more afraid of, failure or success? And why?",
  "How would you describe the feeling of being in love in one word?",
  "When was the last time you surprised yourself?",
  "What's been your happiest memory this past year?",
  "Do you think the image you have of yourself matches the image people see you as?",
  "If you have, when was the moment you realized you weren't invincible?",
  "What lesson took you the longest to unlearn?",
  "What part of your life works? What part of your life hurts?",
  "What is your 1st love's name and the reason you fell in love with him/her?",
  "What's your mother's name? And the most beautiful thing about her?",
  "If you could get to know someone in your life on a deeper level, who would it be and why?",
  "Are you missing anyone right now? Do you think they are missing you too?",
  "What is a dream you've let go of?",
  "What is the last thing you lied to your mother about?",
  "Have you ever told someone I love you but didn't mean it? if so, why?",
  "How can you become a better person?",
  "What can I help you with?",
  "Why do you think we met?",
  "What about me surprised you?",
  "In a word, how would you describe our conversation?",
  "What do you think my strength is?",
  "What can I teach you?",
  "Based on what you've learned about me, do you have any Netflix recommendations?",
  "Who do I remind you of?",
  "What can you be kinder towards yourself for today?",
  "What's one small thing you can do to be a better person in 2019?",
  "What can we create together?",
  "How would you describe me to a stranger?",
  "What about me most surprised you?",
  "What would be the perfect gift for me?",
  "What do you admire most about me?",
  "Based on what you learned about me, what book would you recommend I read?",
  "What about me is hardest for you to understand?",
  "What am I most qualified to give advice about?",
  "What is one thing you think I can do that would dramatically improve my life?",
  "If we were in a band, what would our name be?",
  "Based on what you learned about me, does my social media accurately reflect who I am? Why or why not?",
  "What do I need to hear right now?",
  "Based on what you know about me, do you have any netflix recommendations?",
  "What do you think my superpower is?",
  "What is a lesson you will take away from our conversation?",
  "When in this game did you feel most connected to me?",
  "How does one earn your vulnerability? Have I earned it? How can I earn more?",
  "What do you think our most important similarity is?",
  "In one word, how would you describe our conversation?",
  "What answer of mine made you light up?",
  "When this game is over, what will you remember about me?",
  "What question were you most afraid to answer?",
  "What parts of yourself do you see in me?",
  "How do our personalities complement each other?",
  "What do you think my weakness is?",
  "What would make you feel closer to me?",
  "What do you think I fear the most?",
  "What has this conversation taught you about yourself?",
  "What do you think I should know about myself that perhaps I'm unaware of?",
  "What do you think my defining characterisitic is?",
  "Do you believe everyone has a calling? If so, do you think I've found mine?",
  "What do you recommend I let go of, if anything?",
  "In one word, describe how you feel right now",
];

export const levelTwo = [
  // make questions that couples woudl ask each other
  "How important do you think birthdays and holidays are to me? Explain.",
  "Who do you think was more nervous on our first date? Explain.",
  "What do you think I find most attractive about you?",
  "What do you think I find most annoying about you?",
  "What do you think I find most endearing about you?",
  "What do you think I find most frustrating about you?",
  "What do you think I find most comforting about you?",
  "What do you think I find most confusing about you?",
  "What do you think I find most surprising about you?",
  "What do you think I find most disappointing about you?",
  "What do you think I find most exciting about you?",
  "What do you think I find most boring about you?",
  "What do you think I find most beautiful about you?",
  "What do you think I find most ugly about you?",
  "What do you think I find most interesting about you?",
  "What do you think my perfect date night would be?",
  "What do you think my favorite thing about you is?",
  "What do you think my least favorite thing about you is?",
  "What do you think my favorite thing about us is?",
  "What do you think my least favorite thing about us is?",
  "What was the first thing you noticed about me?",
  "What assumption did you make about me that turned out to be false?",
  "On a scale of 1-10, how open do you feel I am with you? Explain.",
  "What would a day of completely spoiling me look like?",
  "What would a day of completely spoiling you look like?",
  "The hardest thing for me to reveal about myself to you was _________.",
  "How does one earn your trust? Have I earned it? How can I earn more?",
  "What do you think my love language is?",
  "What do you think my attachment style is?",
  "What do you think my biggest fear is?",
  "What do you think my biggest insecurity is?",
  "What do you think my biggest regret is?",
  "What do you think my biggest dream is?",
  "What do you think my biggest secret is?",
  "What do you think my biggest pet peeve is?",
  "What do you think my biggest turn on is?",
  "What do you think my biggest turn off is?",
  "What do you think my biggest strength is?",
  "What do you think my biggest weakness is?",
  "What do you think my biggest accomplishment is?",
  "What do you think my biggest failure is?",
  "What do you think my biggest disappointment is?",
  "What do you think my biggest surprise is?",
  "What has this relationship taught you about yourself?",
  "What do you think I need to hear right now?",
  "What do you think I need to let go of?",
  "What do you think I need to accept?",
  "What do you think I need to forgive myself for?",
  "What's the most romantic thing I've done for you recently?",
  "What's the most romantic thing you've done for me recently?",
  "What's the most romantic thing I've done for you ever?",
  "What's the most romantic thing you've done for me ever?",
  "What's the most romantic thing you've ever done for someone else?",
  "What's the most romantic thing someone has ever done for you?",
  "What's one small way I can be a better partner?",
  "What's the most attractive thing I do without realizing it?",
  "What did our worst argument teach you?",
  "What did our last argument teach you?",
  "What are you currently working through that I don't see, if anything?",
  "What song best describes our relationship?",
  "What's the hardest part about dating me?",
  "Do you think my job affects me positively or negatively? How does it affect us?",
  "What have you been extra sensitive to lately?",
  "What feelings are hard for you to communicate to me? How can I make it easier?",
  "What's the most important thing I've taught you?",
  "What immediately attracted you to me? What attracted you more over time?",
  "On a scale of 1-10 write down the importance of having kids to you. Compare and explain.",
  "What's the best gift I've given you? Material and immaterial.",
  "What about you feels hardest to love?",
  "What do you wish we did more of?",
  "What do you wish we did less of?",
  "What do you think I'm most insecure about?",
  "What do you think I'm most sensitive about?",
  "What made you fall in love with me?",
  "What's the most important lesson a past relationship has taught you?",
  "Finish the sentence: Thank you for accepting ____________. I know it's not easy.",
  "Are there any insecurities from previous relationships that you carried into this one? If so, what are they?",
  "What's the most important thing I've taught you about love?",
  "What recent experience made you feel closer to me?",
  "How do our strengths and weaknesses complement each other?",
  "What's the most important thing I've taught you about yourself?",
  "What have I helped you appreciate about yourself?",
  "How do I show that I love you without telling you?",
  "When was the last time I hurt you, perhaps unintentionally?",
  "How have you seen me grow in this relationship?",
  "Have I helped you change your mind about anything? If so, what?",
  "Is there anything you still don't know about me that you wish you did?",
];

export const levelThree = [
  "How vocal do i seem like i get in bed?",
  "What do you think my age range would be in a dating app?",
  "What makes a good nude?",
  "Whats the most surprising thing that has ever turned you on?",
  "What's the most surprising thing that has ever turned you off?",
  "What sex position always makes you feel the most connected to your partner?",
  "What is the most embarrassing thing that has ever happened to you in bed that you can laugh at now?",
  
];
